name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ref: master

    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    
    - name: Build
      run: |
        yarn install
        yarn build
    
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1.2.4
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      with:
        build_dir: public
