name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
  schedule:
    - cron: '* */12 * * *'

jobs:
  build:
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ref: master

    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    
    - name: Build
      run: |
        npm ci
        npm run build
    
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      with:
        build_dir: public
        keep_history: true
        allow_empty_commit: false
      if: success()
